[phases.setup]
aptPkgs = ["chromium", "chromium-driver"]

[phases.build]
cmds = [
    "pip install -r requirements.txt"
]

[phases.install]
cmds = ["chmod +x start.sh"]

[start]
cmd = "bash start.sh"

[variables]
GOOGLE_CHROME_BIN = "/usr/bin/chromium"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"